---
title: "BB503/BB602/MCB55 - Probability & Statististics - Fall 2022"
output: github_document
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r schedule, echo=FALSE}
suppressMessages(sched_df <- readxl::read_excel("misc/grad_lectures.xlsx"))

sched_df$Slides <- sched_df$`R script` <- NULL
colnames(sched_df)[4] <- "HW"
sched_df$HW[is.na(sched_df$HW)] <- ""

# function for creating link
link_to_file <- function(text, rel_path) {
    URL <- paste0("https://github.com/egeulgen/BB503_BB602_22_23/blob/main/", rel_path)
    new_text <- kableExtra::cell_spec(text, "html", link = URL)
    return(new_text)
}

# links to HWs
sched_df$HW[5] <- link_to_file(sched_df$HW[5], "Homeworks/HW1.pdf")
sched_df$HW[12] <- link_to_file(sched_df$HW[12], "Homeworks/HW2.pdf")

# links to lectures
sched_df$Subject[1] <- link_to_file(sched_df$Subject[1], "lectures/0.intro.pdf")
sched_df$Subject[2] <- link_to_file(sched_df$Subject[2], "lectures/1.descriptive.pdf")
sched_df$Subject[4] <- link_to_file(sched_df$Subject[4], "lectures/3.descriptive.pdf")
sched_df$Subject[5] <- link_to_file(sched_df$Subject[5], "lectures/4.probability.pdf")
sched_df$Subject[6] <- link_to_file(sched_df$Subject[6], "lectures/5.discrete_distributions.pdf")
sched_df$Subject[7] <- link_to_file(sched_df$Subject[7], "lectures/6.continuous_distributions.pdf")
sched_df$Subject[8] <- link_to_file(sched_df$Subject[8], "lectures/7.MLE_LLN_CLT.pdf")
sched_df$Subject[10] <- link_to_file(sched_df$Subject[10], "lectures/9.hypothesis.pdf")
sched_df$Subject[11] <- link_to_file(sched_df$Subject[11], "lectures/10.ANOVA_chi_squared.pdf")
sched_df$Subject[12] <- link_to_file(sched_df$Subject[12], "lectures/11.nonparametric_multiple_testing.pdf")
sched_df$Subject[13] <- link_to_file(sched_df$Subject[13], "lectures/12.Missing_power_linear_regression.pdf")
sched_df$Subject[14] <- link_to_file(sched_df$Subject[14], "lectures/13.glm.pdf")
sched_df$Subject[15] <- link_to_file(sched_df$Subject[15], "lectures/14.resampling.pdf")


# links to R exercises
sched_df$R <- ""
sched_df$R[2] <- link_to_file("Intro", "scripts/1.intro.R")
sched_df$R[4] <- paste(link_to_file("Basics", "scripts/3.1.basics.pdf"), "/", link_to_file("EDA", "scripts/3.2.EDA.pdf"))
sched_df$R[5] <- link_to_file("Prob", "scripts/4.simulation.pdf")
sched_df$R[6] <- link_to_file("Discr. RV", "scripts/5.discrete_distr.pdf")
sched_df$R[7] <- link_to_file("Cont. RV", "scripts/6.cont_distr.pdf")
sched_df$R[10] <- link_to_file("Hypothesis 1", "scripts/9.hypothesis_tests_1.pdf")
sched_df$R[11] <- link_to_file("Hypothesis 2", "scripts/10.hypothesis_tests_2.pdf")
sched_df$R[12] <- link_to_file("Hypothesis 3", "scripts/11.hypothesis_tests_3.pdf")
sched_df$R[13] <- link_to_file("Linear Regression", "scripts/12.linear_regression.pdf")
sched_df$R[14] <- link_to_file("GLM", "scripts/13.glm.pdf")
sched_df$R[15] <- link_to_file("Resampling", "scripts/14.resampling.pdf")

sched_df <- sched_df[, c(1:3, 5, 4)]

kableExtra::row_spec(kableExtra::row_spec(knitr::kable(sched_df, format = "html", escape = FALSE), which(grepl("Midterm", sched_df$Subject)), bold = TRUE, background = "#F4B41A"), nrow(sched_df), bold = TRUE, background = "#E2725A")
```
